# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qm_q9kHymxdKjDUaUQNae5lZKXCY6AN6
"""

import gradio as gr
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
from PIL import Image

# 🔹 تحميل النموذج
model = load_model("best_model_fold_5.keras")

# ✅ دالة التحقق من إن الصورة شكلها X-ray (تباين منخفض)
def is_xray_like(image_array):
    std = np.std(image_array)
    return std < 0.25  # ممكن تعدل القيمة لو عايز تشدد التحقق

# 🔹 دالة التنبؤ
def predict_bone_age(image, sex):
    image = image.resize((299, 299))
    image_array = np.array(image).astype("float32") / 255.0

    if image_array.shape[-1] == 4:
        image_array = image_array[..., :3]

    # ✅ التحقق من إن الصورة X-ray
    if not is_xray_like(image_array):
        return "❌ Please upload a valid grayscale hand X-ray image."

    image_array = np.expand_dims(image_array, axis=0)
    sex_array = np.array([[sex]])

    prediction = model.predict([image_array, sex_array])[0][0]
    predicted_age_months = prediction * 240
    predicted_age_years = predicted_age_months / 12

    return f"🦴 Estimated Bone Age:\n\n**{predicted_age_months:.2f} months**\n**{predicted_age_years:.2f} years**"

# 🔹 وصف للتطبيق
description_text = """
Upload a hand X-ray and select the biological sex to estimate bone age using an AI model trained on Xception architecture.
"""

# 🔹 Gradio واجهة
interface = gr.Interface(
    fn=predict_bone_age,
    inputs=[
        gr.Image(type="pil", label="📷 Hand X-ray Image"),
        gr.Radio(choices=[("👨 Male", 1), ("👩 Female", 0)], label="⚥ Sex", value=1)
    ],
    outputs=gr.Markdown(label="🔍 Result"),
    title="Bone Age Prediction with Xception",
    description=description_text,
)

# 🔹 تشغيل التطبيق
interface.launch()